"""empty message

Revision ID: c5143ef30832
Revises: ec02bf6d4fa8
Create Date: 2024-05-08 15:12:33.078515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5143ef30832'
down_revision = 'ec02bf6d4fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_table', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
