"""empty message

Revision ID: ec02bf6d4fa8
Revises: fd3bbd6d2b72
Create Date: 2024-05-08 14:32:25.428706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec02bf6d4fa8'
down_revision = 'fd3bbd6d2b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=45), nullable=False),
    sa.Column('MiddleName', sa.String(length=45), nullable=True),
    sa.Column('LastName', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_table')
    # ### end Alembic commands ###
